import ImageEvidence from './ImageModel.jsx';
import React,{useEffect,useState} from 'react';
import {Download,FlaskConical,ArrowUpRight} from 'lucide-react';
const score=n=>(100*(n||0)).toFixed(1)+'%';
export default function Evidence(){
 const [metrics,setMetrics]=useState(null),[error,setError]=useState(''),[target,setTarget]=useState('category');
 useEffect(()=>{const controller=new AbortController();fetch('/api/metrics',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Cannot load model evidence');return r.json()}).then(setMetrics).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[]);
 const evaluation=metrics?.[target]?.test;
 return <>
  <div className="page-heading"><div><p className="eyebrow">TRAINED. MEASURED. EXPLAINED.</p><h1>The evidence behind the AI.</h1><p>Multilingual complaint classification, with a test set kept out of training.</p></div><a href="/api/dataset" className="secondary"><Download size={17}/>Download training dataset</a></div>
  {error&&<p role="alert">{error}</p>}{!metrics&&!error&&<p role="status">Loading experiment results…</p>}
  {metrics&&<>
   <div className="alert warning"><FlaskConical size={20}/><span>CivicComp supplies Bengaluru-derived complaints and translations. Lucknow examples supplement training. These results do not establish accuracy on Lucknow citizens.</span></div>
   <div className="stats"><div className="stat"><span>Total text examples</span><strong>{metrics.rows.toLocaleString()}</strong><small>{metrics.audit.downloaded_records.toLocaleString()} source records before cleaning</small></div>{['train','validation','test'].map(s=><div className="stat" key={s}><span>{s==='train'?'Used to train':s==='validation'?'Used to choose model':'Held-out test'}</span><strong>{metrics.splits[s].toLocaleString()}</strong><small>{s==='train'?'External data + authored support':'External complaints only'}</small></div>)}</div>
   <div className="two-col">{['category','urgency'].map(t=><section className="panel" key={t}><p className="eyebrow">{t==='category'?'WHICH DEPARTMENT?':'HOW URGENT?'}</p><h2>{t==='category'?'Category classifier':'Priority classifier'}</h2><div className="metric-number">{score(metrics[t].test.report['macro avg']['f1-score'])}<span>test macro F1</span></div><p>Test accuracy <strong>{score(metrics[t].test.report.accuracy)}</strong> · {metrics.splits.test.toLocaleString()} examples</p><p className="footnote">Macro F1 gives each class equal weight. Accuracy counts all correct predictions.</p><table><thead><tr><th>Validation comparison</th><th>Macro F1</th></tr></thead><tbody>{Object.entries(metrics.comparisons[t].validation_macro_f1).map(([name,v])=><tr key={name}><td>{name==='word'?'Word features':'Word + character features'}{metrics.comparisons[t].selected===name?' · selected':''}</td><td>{score(v)}</td></tr>)}</tbody></table></section>)}</div>
   <section className="panel evidence-detail"><div className="section-title"><div><h2>Look beyond one score</h2><p>Per-class results expose where human review matters.</p></div><select aria-label="Evaluation target" value={target} onChange={e=>setTarget(e.target.value)}><option value="category">Category</option><option value="urgency">Priority</option></select></div><div className="table-wrap"><table><thead><tr><th>Class</th><th>Precision</th><th>Recall</th><th>F1</th><th>Test examples</th></tr></thead><tbody>{evaluation.labels.map(label=>{const r=evaluation.report[label];return <tr key={label}><td>{label}</td><td>{score(r.precision)}</td><td>{score(r.recall)}</td><td>{score(r['f1-score'])}</td><td>{r.support}</td></tr>})}</tbody></table></div><p className="footnote">Sewerage has very little external test support. Its drainage label is broad, so ownership and officer review remain necessary.</p><h3>Performance by language</h3><div className="table-wrap"><table><thead><tr><th>Language</th><th>Macro F1</th><th>Accuracy</th><th>Examples</th></tr></thead><tbody>{Object.entries(metrics[target].by_language).map(([lang,r])=><tr key={lang}><td>{lang}</td><td>{score(r.report['macro avg']['f1-score'])}</td><td>{score(r.report.accuracy)}</td><td>{r.report['macro avg'].support}</td></tr>)}</tbody></table></div><details><summary>Inspect the confusion matrix</summary><p>Rows are actual labels; columns are predictions. Correct predictions lie on the diagonal.</p><div className="table-wrap"><table><thead><tr><th>Actual / predicted</th>{evaluation.labels.map(l=><th key={l}>{l}</th>)}</tr></thead><tbody>{evaluation.confusion_matrix.map((row,i)=><tr key={i}><th>{evaluation.labels[i]}</th>{row.map((v,j)=><td key={j} style={i===j?{background:'#e7f3ed',fontWeight:700}:{}}>{v}</td>)}</tr>)}</tbody></table></div></details></section>
   <section className="panel explanation"><h2>A reproducible experiment</h2><p>{metrics.method}</p><p>{metrics.audit.split_policy}</p><p>After cleaning: <strong>{metrics.audit.external_texts_after_cleaning.toLocaleString()} external text examples</strong> and <strong>{metrics.audit.synthetic_training_texts.toLocaleString()} authored training examples</strong>. {metrics.audit.conflicting_records_removed} source records in contradictory duplicate groups were excluded. Translations are examples of the same complaint, not additional independent citizens.</p><p>{metrics.limitations}</p><p>Scores evaluate raw classifiers. Jurisdiction and safety rules run afterward. Officers can correct department and priority with an action note; the original prediction remains in the record.</p><p>Duplicate suggestions use word similarity ≥ 0.72, distance ≤ 150 metres, matching category and age ≤ 7 days. Resolved reports are excluded. These are prototype thresholds.</p><a href={metrics.source} target="_blank" rel="noreferrer">View CivicComp on Kaggle <ArrowUpRight size={14}/></a><p className="footnote">Source creators: Vivek Mathew and Haji Shariefullah via OpenCity. CivicComp enhancements: Shyam Tripathi, Kothamsu Hridayesh, K. Ashwini and Kritika Agrahari, Amrita Vishwa Vidyapeetham, Chennai Campus. Adapted by cleaning text, grouping splits and mapping labels. <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>.</p><details><summary>Reproduction details</summary><p>Run <code>npm run train</code>. Random seed {metrics.seed}. Dataset SHA-256:</p><code style={{overflowWrap:'anywhere'}}>{metrics.dataset_sha256}</code></details></section>
  </>}
  <ImageEvidence/>
 </>;
}
