"""Prepare honest website metrics for the CLIP candidate; no deployment."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];run=ROOT/'data/image-v6-clip-run'
new=json.loads((run/'metrics.json').read_text());m=json.loads((ROOT/'data/image_metrics.json').read_text())
m.update(modelVersion='image-v6-clip',architecture=new['architecture'],pretraining='OpenAI CLIP ViT-B/32, frozen',training='Frozen image embeddings; supervised multinomial Logistic Regression fit on the training split. Regularization and semantic blend selected by validation macro F1.',history=[],best_epoch=None,epochs_run=0,trainingTrials=new['trials'],classifierTraining=new['selected'],test={'report':new['test'],'labels':new['labels'],'confusion_matrix':new['confusion_matrix']},test_group_report=new['group_test'],validation={'report':new['validation']},selective_test=new['selective_test'],model_sha256=new['checkpoint_sha256'],model_artifact='ml/clip_classifier.joblib',training_seconds=new['fit_seconds'])
m['calibration']={'temperature':new['selected']['temperature'],'class_thresholds':new['class_thresholds'],'validation_threshold_evidence':new['validation_threshold_evidence'],'policy':'Temperature and acceptance thresholds fitted on validation only. Only garbage and pothole may provide accepted photo suggestions; >=90% observed precision on >=20 validation images, score >=.70 and top-two margin >=.15. This is not a guarantee on arbitrary images.'}
m['limitations']='Frozen pretrained CLIP encoder with a project-trained civic head, not a CNN trained from scratch. Same existing source-group test split as earlier experiments; not a fresh external Lucknow benchmark. Dataset shortcuts and unsupported confident predictions remain possible. The supplied pothole photograph was excluded from project training and selection; exposure during original web pretraining is unknown. Sign scenes and streetlight infrastructure do not establish defects or outages.'
m['encoder_revision']=(ROOT/'data/clip-pretrained/revision.txt').read_text().strip()
m['sources'].append({'name':'OpenAI CLIP ViT-B/32 pretrained encoder','url':'https://huggingface.co/openai/clip-vit-base-patch32','scope':'Pretrained visual features; not additional project training photos.'})
(run/'website_metrics.json').write_text(json.dumps(m,indent=2));print('Prepared candidate website metrics')
