from pathlib import Path
p=Path('frontend/main.jsx')
s=p.read_text(encoding='utf-8-sig')
s=s.replace("import './polish.css';", "import './polish.css';\nimport './hero.css';\nimport lucknowPhoto from './assets/lucknow-hero.jpg';")
start=s.index(" {page==='overview'&&<>")
end=s.index('<div className="stats">',start)
s=s[:start]+''' {page==='overview'&&<><section className="landmark-hero" aria-labelledby="city-hero-title"><img className="landmark-photo" src={lucknowPhoto} alt="Rumi Darwaza, Lucknow, with its ornate gateway and lively streets" fetchPriority="high"/><div className="landmark-shade"/><div className="landmark-top"><span><MapPinned size={14}/> LUCKNOW, UTTAR PRADESH</span><span className="hero-hindi">मेरा शहर, मेरी ज़िम्मेदारी</span></div><div className="landmark-copy"><p className="landmark-eyebrow">A CITY WE LOVE. A CITY WE CARE FOR.</p><h1 id="city-hero-title">Our city.<br/><em>Our responsibility.</em></h1><p>From its iconic gateways to your everyday streets.<br/>Help make Lucknow cleaner, safer and better —<br className="desktop-break"/> one report at a time.</p><div className="landmark-actions"><button className="landmark-cta" onClick={()=>navigate(user.role==='citizen'?'report':'complaints')}>{user.role==='citizen'?'Report an issue':'Open your work queue'}<ArrowUpRight size={19}/></button><button className="landmark-secondary" onClick={()=>navigate('complaints')}>Track reports <ArrowRight size={17}/></button></div></div><div className="landmark-bottom"><span><span className="photo-dot"/> Rumi Darwaza <small>THE HEART OF OLD LUCKNOW</small></span><a href="https://commons.wikimedia.org/wiki/File:Rumi_Darwaja_(Rumi_Gate).jpg" target="_blank" rel="noreferrer">Photo: Aryanmathurphotography · CC BY-SA 4.0 <ArrowUpRight size={12}/></a></div></section><div className="civic-path"><div><span>01</span><p><b>Make your voice heard</b><small>Describe the issue in your neighbourhood</small></p></div><ArrowRight size={16}/><div><span>02</span><p><b>Reach the right desk</b><small>Get a suggested department and officer role</small></p></div><ArrowRight size={16}/><div><span>03</span><p><b>Follow the progress</b><small>See updates from report to resolution</small></p></div></div>''' + s[end:]
s=s.replace('<section className="login-story"><div className="brand">','<section className="login-story"><img className="login-landmark" src={lucknowPhoto} alt="Rumi Darwaza in Lucknow" fetchPriority="high"/><div className="brand">')
s=s.replace('<h1>Your voice.<br/>Your neighbourhood.<br/><em>A visible response.</em></h1>', '<h1>A city worth<br/>caring for.<br/><em>A voice that matters.</em></h1>')
s=s.replace('Independent student project; not an official government service.</small></section>', 'Independent student project; not an official government service.<br/><a href="https://commons.wikimedia.org/wiki/File:Rumi_Darwaja_(Rumi_Gate).jpg" target="_blank" rel="noreferrer">Photo: Aryanmathurphotography · CC BY-SA 4.0</a></small></section>')
p.write_text(s,encoding='utf8')
